camera_info:
  image_width: 800
  image_height: 600
stop_line_positions:
    - [1148.56, 1184.65]
    - [1559.2, 1158.43]
    - [2122.14, 1526.79]
    - [2175.237, 1795.71]
    - [1493.29, 2947.67]
    - [821.96, 2905.8]
    - [161.76, 2303.82]
    - [351.84, 1574.65]
classification:
  model: '/light_classification/classifier/model_data/yolo_sim.h5'
  anchors: '/light_classification/classifier/model_data/tiny_yolo_anchors.txt'
  classes: '/light_classification/classifier/model_data/traffic_light_classes.txt'
  is_carla: false
