camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
classification:
  model: '/light_classification/classifier/model_data/yolo_carla.h5'
  anchors: '/light_classification/classifier/model_data/tiny_yolo_anchors.txt'
  classes: '/light_classification/classifier/model_data/traffic_light_classes.txt'
  is_carla: true